export type PanelStoreRow = {
  id: string;
  name: string;
  region: string;
  address: string;
  reason?: string;
  date?: string;
  priority?: "Cao" | "Trung bình" | "Thấp";
  evidenceStatus?: string;
  gbpState?: string;
  rating?: number;
  reviewCount?: number;
  oneStarCount?: number;
  phone?: string;
  kanban?: string;
};

export const SUSPENDED_STORES_DETAIL: PanelStoreRow[] = [
  {
    id: "store-0003",
    name: "Vinamilk Hà Nội — CH 3",
    region: "Hà Nội",
    address: "102 Đường 3, Quận 4, Hà Nội",
    reason: "Vi phạm chính sách hình ảnh (logo không khớp)",
    date: "13/08/2026 08:12",
    gbpState: "Suspended",
    evidenceStatus: "Thiếu video mặt tiền",
  },
  {
    id: "store-0018",
    name: "Vinamilk TP.HCM — CH 18",
    region: "TP.HCM",
    address: "118 Đường 18, Quận 7, TP.HCM",
    reason: "N.A.P không khớp với giấy phép kinh doanh",
    date: "13/08/2026 06:40",
    gbpState: "Suspended",
    evidenceStatus: "Đã nộp giấy phép",
  },
  {
    id: "store-0041",
    name: "Vinamilk Miền Nam — CH 41",
    region: "Miền Nam",
    address: "141 Đường 41, Quận 6, Miền Nam",
    reason: "Trùng listing / duplicate GBP",
    date: "12/08/2026 21:05",
    gbpState: "Suspended",
    evidenceStatus: "Chưa nộp",
  },
  {
    id: "store-0055",
    name: "Vinamilk Miền Bắc — CH 55",
    region: "Miền Bắc",
    address: "155 Đường 5, Quận 8, Miền Bắc",
    reason: "Video mặt tiền không thấy bảng hiệu",
    date: "12/08/2026 18:22",
    gbpState: "Suspended",
    evidenceStatus: "Cần quay lại",
  },
  {
    id: "store-0072",
    name: "Vinamilk Miền Trung — CH 72",
    region: "Miền Trung",
    address: "172 Đường 22, Quận 1, Miền Trung",
    reason: "Địa chỉ không xác minh được trên Street View",
    date: "12/08/2026 14:10",
    gbpState: "Suspended",
    evidenceStatus: "Thiếu ảnh bảng hiệu",
  },
  {
    id: "store-0088",
    name: "Vinamilk Hà Nội — CH 88",
    region: "Hà Nội",
    address: "188 Đường 38, Quận 5, Hà Nội",
    reason: "SĐT không liên lạc được khi Google gọi xác minh",
    date: "12/08/2026 11:48",
    gbpState: "Suspended",
    evidenceStatus: "Đã nộp đủ",
  },
  {
    id: "store-0104",
    name: "Vinamilk TP.HCM — CH 104",
    region: "TP.HCM",
    address: "104 Đường 4, Quận 9, TP.HCM",
    reason: "Category không đúng ngành hàng",
    date: "12/08/2026 09:30",
    gbpState: "Suspended",
    evidenceStatus: "Chờ Manager duyệt",
  },
  {
    id: "store-0120",
    name: "Vinamilk Miền Nam — CH 120",
    region: "Miền Nam",
    address: "120 Đường 20, Quận 1, Miền Nam",
    reason: "Vi phạm chính sách hình ảnh (logo không khớp)",
    date: "11/08/2026 22:15",
    gbpState: "Suspended",
    evidenceStatus: "Thiếu video mặt tiền",
  },
  {
    id: "store-0136",
    name: "Vinamilk Miền Bắc — CH 136",
    region: "Miền Bắc",
    address: "136 Đường 36, Quận 5, Miền Bắc",
    reason: "N.A.P không khớp với giấy phép kinh doanh",
    date: "11/08/2026 16:02",
    gbpState: "Suspended",
    evidenceStatus: "Đã nộp giấy phép",
  },
  {
    id: "store-0152",
    name: "Vinamilk Miền Trung — CH 152",
    region: "Miền Trung",
    address: "152 Đường 2, Quận 9, Miền Trung",
    reason: "Trùng listing / duplicate GBP",
    date: "11/08/2026 10:44",
    gbpState: "Suspended",
    evidenceStatus: "Chưa nộp",
  },
  {
    id: "store-0168",
    name: "Vinamilk Hà Nội — CH 168",
    region: "Hà Nội",
    address: "168 Đường 18, Quận 1, Hà Nội",
    reason: "Video mặt tiền không thấy bảng hiệu",
    date: "11/08/2026 08:18",
    gbpState: "Suspended",
    evidenceStatus: "Cần quay lại",
  },
  {
    id: "store-0184",
    name: "Vinamilk TP.HCM — CH 184",
    region: "TP.HCM",
    address: "184 Đường 34, Quận 5, TP.HCM",
    reason: "Địa chỉ không xác minh được trên Street View",
    date: "10/08/2026 19:55",
    gbpState: "Suspended",
    evidenceStatus: "Thiếu ảnh bảng hiệu",
  },
];

export const CLAIM_STORES_DETAIL: PanelStoreRow[] = [
  {
    id: "store-0201",
    name: "Vinamilk TP.HCM — CH 201",
    region: "TP.HCM",
    address: "201 Đường 1, Quận 1, TP.HCM",
    priority: "Cao",
    gbpState: "Claim",
    reason: "Chưa có listing GBP — ưu tiên vì traffic cao",
  },
  {
    id: "store-0215",
    name: "Vinamilk Hà Nội — CH 215",
    region: "Hà Nội",
    address: "215 Đường 15, Quận 3, Hà Nội",
    priority: "Cao",
    gbpState: "Claim",
    reason: "Cửa hàng mới khai trương tháng 7",
  },
  {
    id: "store-0230",
    name: "Vinamilk Miền Nam — CH 230",
    region: "Miền Nam",
    address: "230 Đường 30, Quận 5, Miền Nam",
    priority: "Trung bình",
    gbpState: "Claim",
    reason: "Chưa gán Place ID",
  },
  {
    id: "store-0244",
    name: "Vinamilk Miền Bắc — CH 244",
    region: "Miền Bắc",
    address: "244 Đường 44, Quận 8, Miền Bắc",
    priority: "Trung bình",
    gbpState: "Claim",
    reason: "Listing tồn tại nhưng chưa claim",
  },
  {
    id: "store-0258",
    name: "Vinamilk Miền Trung — CH 258",
    region: "Miền Trung",
    address: "258 Đường 8, Quận 11, Miền Trung",
    priority: "Thấp",
    gbpState: "Claim",
    reason: "Khu vực ít search volume",
  },
  {
    id: "store-0272",
    name: "Vinamilk TP.HCM — CH 272",
    region: "TP.HCM",
    address: "272 Đường 22, Quận 3, TP.HCM",
    priority: "Cao",
    gbpState: "Claim",
    reason: "Đối thủ đã có GBP cùng khu",
  },
  {
    id: "store-0286",
    name: "Vinamilk Hà Nội — CH 286",
    region: "Hà Nội",
    address: "286 Đường 36, Quận 7, Hà Nội",
    priority: "Trung bình",
    gbpState: "Claim",
    reason: "Chưa có listing GBP",
  },
  {
    id: "store-0300",
    name: "Vinamilk Miền Nam — CH 300",
    region: "Miền Nam",
    address: "300 Đường 50, Quận 1, Miền Nam",
    priority: "Thấp",
    gbpState: "Claim",
    reason: "Chờ Store Manager xác nhận địa chỉ",
  },
  {
    id: "store-0314",
    name: "Vinamilk Miền Bắc — CH 314",
    region: "Miền Bắc",
    address: "314 Đường 14, Quận 3, Miền Bắc",
    priority: "Cao",
    gbpState: "Claim",
    reason: "Cửa hàng flagship khu vực",
  },
  {
    id: "store-0328",
    name: "Vinamilk Miền Trung — CH 328",
    region: "Miền Trung",
    address: "328 Đường 28, Quận 5, Miền Trung",
    priority: "Trung bình",
    gbpState: "Claim",
    reason: "Chưa gán Place ID",
  },
];

export const NEW_STORES_DETAIL: PanelStoreRow[] = [
  {
    id: "store-0340",
    name: "Vinamilk TP.HCM — CH 340",
    region: "TP.HCM",
    address: "340 Đường 40, Quận 5, TP.HCM",
    gbpState: "New",
    date: "10/08/2026",
    evidenceStatus: "Chờ import NAP",
  },
  {
    id: "store-0355",
    name: "Vinamilk Hà Nội — CH 355",
    region: "Hà Nội",
    address: "355 Đường 5, Quận 8, Hà Nội",
    gbpState: "New",
    date: "09/08/2026",
    evidenceStatus: "Đã import, chờ tag",
  },
  {
    id: "store-0370",
    name: "Vinamilk Miền Nam — CH 370",
    region: "Miền Nam",
    address: "370 Đường 20, Quận 11, Miền Nam",
    gbpState: "New",
    date: "08/08/2026",
    evidenceStatus: "Chờ Store Manager",
  },
  {
    id: "store-0385",
    name: "Vinamilk Miền Bắc — CH 385",
    region: "Miền Bắc",
    address: "385 Đường 35, Quận 2, Miền Bắc",
    gbpState: "New",
    date: "07/08/2026",
    evidenceStatus: "Chờ import NAP",
  },
  {
    id: "store-0400",
    name: "Vinamilk Miền Trung — CH 400",
    region: "Miền Trung",
    address: "400 Đường 50, Quận 5, Miền Trung",
    gbpState: "New",
    date: "06/08/2026",
    evidenceStatus: "Đã import, chờ tag",
  },
];

export const VERIFY_STORES_DETAIL: PanelStoreRow[] = [
  {
    id: "store-0042",
    name: "Vinamilk TP.HCM — CH 42",
    region: "TP.HCM",
    address: "123 Đường Nguyễn Huệ, Quận 1, TP.HCM",
    gbpState: "Verify",
    evidenceStatus: "Thiếu video mặt tiền",
    date: "Hạn nộp 20/08/2026",
  },
  {
    id: "store-0060",
    name: "Vinamilk Hà Nội — CH 60",
    region: "Hà Nội",
    address: "160 Đường 10, Quận 1, Hà Nội",
    gbpState: "Verify",
    evidenceStatus: "Đã nộp đủ — chờ Google",
    date: "Nộp 11/08/2026",
  },
  {
    id: "store-0078",
    name: "Vinamilk Miền Nam — CH 78",
    region: "Miền Nam",
    address: "178 Đường 28, Quận 7, Miền Nam",
    gbpState: "Verify",
    evidenceStatus: "Thiếu giấy phép",
    date: "Hạn nộp 18/08/2026",
  },
  {
    id: "store-0096",
    name: "Vinamilk Miền Bắc — CH 96",
    region: "Miền Bắc",
    address: "196 Đường 46, Quận 1, Miền Bắc",
    gbpState: "Verify",
    evidenceStatus: "Chờ Manager duyệt",
    date: "Nộp 12/08/2026",
  },
  {
    id: "store-0114",
    name: "Vinamilk Miền Trung — CH 114",
    region: "Miền Trung",
    address: "114 Đường 14, Quận 3, Miền Trung",
    gbpState: "Verify",
    evidenceStatus: "Đã nộp đủ — chờ Google",
    date: "Nộp 09/08/2026",
  },
];

export const FUNNEL_STAGE_STORES: Record<string, PanelStoreRow[]> = {
  "Tổng cửa hàng": [
    ...CLAIM_STORES_DETAIL.slice(0, 3),
    ...SUSPENDED_STORES_DETAIL.slice(0, 3),
    ...VERIFY_STORES_DETAIL.slice(0, 4),
  ],
  Verify: VERIFY_STORES_DETAIL,
  "Đã nộp bằng chứng": [
    {
      id: "store-0060",
      name: "Vinamilk Hà Nội — CH 60",
      region: "Hà Nội",
      address: "160 Đường 10, Quận 1, Hà Nội",
      gbpState: "Verify",
      evidenceStatus: "Đã nộp đủ — chờ Google",
    },
    {
      id: "store-0096",
      name: "Vinamilk Miền Bắc — CH 96",
      region: "Miền Bắc",
      address: "196 Đường 46, Quận 1, Miền Bắc",
      gbpState: "Verify",
      evidenceStatus: "Chờ Manager duyệt",
    },
    {
      id: "store-0114",
      name: "Vinamilk Miền Trung — CH 114",
      region: "Miền Trung",
      address: "114 Đường 14, Quận 3, Miền Trung",
      gbpState: "Verify",
      evidenceStatus: "Đã nộp đủ — chờ Google",
    },
    {
      id: "store-0018",
      name: "Vinamilk TP.HCM — CH 18",
      region: "TP.HCM",
      address: "118 Đường 18, Quận 7, TP.HCM",
      gbpState: "Suspended",
      evidenceStatus: "Đã nộp giấy phép",
    },
    {
      id: "store-0088",
      name: "Vinamilk Hà Nội — CH 88",
      region: "Hà Nội",
      address: "188 Đường 38, Quận 5, Hà Nội",
      gbpState: "Suspended",
      evidenceStatus: "Đã nộp đủ",
    },
  ],
  Verified: [
    {
      id: "store-0001",
      name: "Vinamilk TP.HCM — CH 1",
      region: "TP.HCM",
      address: "1 Đường Lê Lợi, Quận 1, TP.HCM",
      gbpState: "Verified",
      evidenceStatus: "Verified 02/08/2026",
    },
    {
      id: "store-0007",
      name: "Vinamilk Hà Nội — CH 7",
      region: "Hà Nội",
      address: "7 Đường Tràng Tiền, Hoàn Kiếm, Hà Nội",
      gbpState: "Verified",
      evidenceStatus: "Verified 04/08/2026",
    },
    {
      id: "store-0012",
      name: "Vinamilk Miền Nam — CH 12",
      region: "Miền Nam",
      address: "12 Đường 30/4, Ninh Kiều, Cần Thơ",
      gbpState: "Verified",
      evidenceStatus: "Verified 05/08/2026",
    },
  ],
};

export const REVIEW_BREAKDOWN = [
  { region: "TP.HCM", current: 820, target: 2000, oneStar: 48 },
  { region: "Hà Nội", current: 610, target: 1800, oneStar: 31 },
  { region: "Miền Nam", current: 390, target: 1200, oneStar: 22 },
  { region: "Miền Bắc", current: 210, target: 900, oneStar: 14 },
  { region: "Miền Trung", current: 150, target: 600, oneStar: 9 },
];

export const REVIEW_TOP_ONE_STAR: PanelStoreRow[] = [
  {
    id: "store-0042",
    name: "Vinamilk TP.HCM — CH 42",
    region: "TP.HCM",
    address: "123 Đường Nguyễn Huệ, Quận 1, TP.HCM",
    rating: 3.4,
    reviewCount: 38,
    oneStarCount: 9,
  },
  {
    id: "store-0018",
    name: "Vinamilk TP.HCM — CH 18",
    region: "TP.HCM",
    address: "118 Đường 18, Quận 7, TP.HCM",
    rating: 3.6,
    reviewCount: 52,
    oneStarCount: 7,
  },
  {
    id: "store-0088",
    name: "Vinamilk Hà Nội — CH 88",
    region: "Hà Nội",
    address: "188 Đường 38, Quận 5, Hà Nội",
    rating: 3.8,
    reviewCount: 41,
    oneStarCount: 6,
  },
  {
    id: "store-0072",
    name: "Vinamilk Miền Trung — CH 72",
    region: "Miền Trung",
    address: "172 Đường 22, Quận 1, Miền Trung",
    rating: 3.9,
    reviewCount: 29,
    oneStarCount: 5,
  },
  {
    id: "store-0055",
    name: "Vinamilk Miền Bắc — CH 55",
    region: "Miền Bắc",
    address: "155 Đường 5, Quận 8, Miền Bắc",
    rating: 4.0,
    reviewCount: 33,
    oneStarCount: 4,
  },
];

export const STORE_LIST_MANAGER: PanelStoreRow[] = [
  {
    id: "store-0042",
    name: "Vinamilk TP.HCM — CH 42",
    region: "TP.HCM",
    address: "123 Đường Nguyễn Huệ, Quận 1, TP.HCM",
    phone: "02812340042",
    gbpState: "Verify",
    evidenceStatus: "Thiếu video mặt tiền",
    kanban: "Cần thu thập bằng chứng",
    rating: 3.4,
    reviewCount: 38,
  },
  {
    id: "store-0003",
    name: "Vinamilk Hà Nội — CH 3",
    region: "Hà Nội",
    address: "102 Đường 3, Quận 4, Hà Nội",
    phone: "02812340003",
    gbpState: "Suspended",
    evidenceStatus: "Thiếu video mặt tiền",
    kanban: "Cần thu thập bằng chứng",
    rating: 4.1,
    reviewCount: 22,
  },
  {
    id: "store-0018",
    name: "Vinamilk TP.HCM — CH 18",
    region: "TP.HCM",
    address: "118 Đường 18, Quận 7, TP.HCM",
    phone: "02812340018",
    gbpState: "Suspended",
    evidenceStatus: "Đã nộp giấy phép",
    kanban: "Chờ Google duyệt",
    rating: 3.6,
    reviewCount: 52,
  },
  {
    id: "store-0001",
    name: "Vinamilk TP.HCM — CH 1",
    region: "TP.HCM",
    address: "1 Đường Lê Lợi, Quận 1, TP.HCM",
    phone: "02812340001",
    gbpState: "Verified",
    evidenceStatus: "Đã nộp đủ",
    kanban: "Thành công",
    rating: 4.7,
    reviewCount: 86,
  },
  {
    id: "store-0060",
    name: "Vinamilk Hà Nội — CH 60",
    region: "Hà Nội",
    address: "160 Đường 10, Quận 1, Hà Nội",
    phone: "02812340060",
    gbpState: "Verify",
    evidenceStatus: "Đã nộp đủ — chờ Google",
    kanban: "Chờ Google duyệt",
    rating: 4.3,
    reviewCount: 19,
  },
  {
    id: "store-0078",
    name: "Vinamilk Miền Nam — CH 78",
    region: "Miền Nam",
    address: "178 Đường 28, Quận 7, Miền Nam",
    phone: "02812340078",
    gbpState: "Verify",
    evidenceStatus: "Thiếu giấy phép",
    kanban: "Cần thu thập bằng chứng",
    rating: 4.0,
    reviewCount: 11,
  },
  {
    id: "store-0201",
    name: "Vinamilk TP.HCM — CH 201",
    region: "TP.HCM",
    address: "201 Đường 1, Quận 1, TP.HCM",
    phone: "02812340201",
    gbpState: "Claim",
    evidenceStatus: "Chưa nộp",
    kanban: "Cần thu thập bằng chứng",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "store-0215",
    name: "Vinamilk Hà Nội — CH 215",
    region: "Hà Nội",
    address: "215 Đường 15, Quận 3, Hà Nội",
    phone: "02812340215",
    gbpState: "Claim",
    evidenceStatus: "Chưa nộp",
    kanban: "Cần thu thập bằng chứng",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "store-0340",
    name: "Vinamilk TP.HCM — CH 340",
    region: "TP.HCM",
    address: "340 Đường 40, Quận 5, TP.HCM",
    phone: "02812340340",
    gbpState: "New",
    evidenceStatus: "Chờ import NAP",
    kanban: "Cần thu thập bằng chứng",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "store-0007",
    name: "Vinamilk Hà Nội — CH 7",
    region: "Hà Nội",
    address: "7 Đường Tràng Tiền, Hoàn Kiếm, Hà Nội",
    phone: "02812340007",
    gbpState: "Verified",
    evidenceStatus: "Đã nộp đủ",
    kanban: "Thành công",
    rating: 4.6,
    reviewCount: 64,
  },
  {
    id: "store-0041",
    name: "Vinamilk Miền Nam — CH 41",
    region: "Miền Nam",
    address: "141 Đường 41, Quận 6, Miền Nam",
    phone: "02812340041",
    gbpState: "Suspended",
    evidenceStatus: "Chưa nộp",
    kanban: "Cần thu thập bằng chứng",
    rating: 3.9,
    reviewCount: 17,
  },
  {
    id: "store-0055",
    name: "Vinamilk Miền Bắc — CH 55",
    region: "Miền Bắc",
    address: "155 Đường 5, Quận 8, Miền Bắc",
    phone: "02812340055",
    gbpState: "Suspended",
    evidenceStatus: "Cần quay lại",
    kanban: "Cần thu thập bằng chứng",
    rating: 4.0,
    reviewCount: 33,
  },
  {
    id: "store-0072",
    name: "Vinamilk Miền Trung — CH 72",
    region: "Miền Trung",
    address: "172 Đường 22, Quận 1, Miền Trung",
    phone: "02812340072",
    gbpState: "Suspended",
    evidenceStatus: "Thiếu ảnh bảng hiệu",
    kanban: "Cần thu thập bằng chứng",
    rating: 3.9,
    reviewCount: 29,
  },
  {
    id: "store-0096",
    name: "Vinamilk Miền Bắc — CH 96",
    region: "Miền Bắc",
    address: "196 Đường 46, Quận 1, Miền Bắc",
    phone: "02812340096",
    gbpState: "Verify",
    evidenceStatus: "Chờ Manager duyệt",
    kanban: "Đã tải video",
    rating: 4.2,
    reviewCount: 14,
  },
  {
    id: "store-0114",
    name: "Vinamilk Miền Trung — CH 114",
    region: "Miền Trung",
    address: "114 Đường 14, Quận 3, Miền Trung",
    phone: "02812340114",
    gbpState: "Verify",
    evidenceStatus: "Đã nộp đủ — chờ Google",
    kanban: "Chờ Google duyệt",
    rating: 4.4,
    reviewCount: 21,
  },
  {
    id: "store-0012",
    name: "Vinamilk Miền Nam — CH 12",
    region: "Miền Nam",
    address: "12 Đường 30/4, Ninh Kiều, Cần Thơ",
    phone: "02812340012",
    gbpState: "Verified",
    evidenceStatus: "Đã nộp đủ",
    kanban: "Thành công",
    rating: 4.5,
    reviewCount: 40,
  },
  {
    id: "store-0230",
    name: "Vinamilk Miền Nam — CH 230",
    region: "Miền Nam",
    address: "230 Đường 30, Quận 5, Miền Nam",
    phone: "02812340230",
    gbpState: "Claim",
    evidenceStatus: "Chưa nộp",
    kanban: "Cần thu thập bằng chứng",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "store-0355",
    name: "Vinamilk Hà Nội — CH 355",
    region: "Hà Nội",
    address: "355 Đường 5, Quận 8, Hà Nội",
    phone: "02812340355",
    gbpState: "New",
    evidenceStatus: "Đã import, chờ tag",
    kanban: "Cần thu thập bằng chứng",
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "store-0088",
    name: "Vinamilk Hà Nội — CH 88",
    region: "Hà Nội",
    address: "188 Đường 38, Quận 5, Hà Nội",
    phone: "02812340088",
    gbpState: "Suspended",
    evidenceStatus: "Đã nộp đủ",
    kanban: "Chờ Google duyệt",
    rating: 3.8,
    reviewCount: 41,
  },
  {
    id: "store-0104",
    name: "Vinamilk TP.HCM — CH 104",
    region: "TP.HCM",
    address: "104 Đường 4, Quận 9, TP.HCM",
    phone: "02812340104",
    gbpState: "Suspended",
    evidenceStatus: "Chờ Manager duyệt",
    kanban: "Đã tải video",
    rating: 4.1,
    reviewCount: 27,
  },
];

export const WEEKLY_PROGRESS_BY_PROVINCE = [
  { province: "TP.HCM", verified: 18, pending: 42, suspended: 22, reviews: 820 },
  { province: "Hà Nội", verified: 12, pending: 38, suspended: 19, reviews: 610 },
  { province: "Cần Thơ", verified: 4, pending: 16, suspended: 8, reviews: 140 },
  { province: "Đà Nẵng", verified: 3, pending: 14, suspended: 7, reviews: 95 },
  { province: "Hải Phòng", verified: 2, pending: 11, suspended: 6, reviews: 70 },
  { province: "Bình Dương", verified: 3, pending: 18, suspended: 9, reviews: 125 },
];

export const WEEKLY_REVIEW_KPI = [
  { region: "TP.HCM", rating: 4.2, reviews: 820, replied: 710, slaHours: 6 },
  { region: "Hà Nội", rating: 4.1, reviews: 610, replied: 540, slaHours: 8 },
  { region: "Miền Nam", rating: 4.0, reviews: 390, replied: 310, slaHours: 10 },
  { region: "Miền Bắc", rating: 3.9, reviews: 210, replied: 160, slaHours: 12 },
  { region: "Miền Trung", rating: 4.0, reviews: 150, replied: 118, slaHours: 11 },
];

export const STORE_MANAGER_OVERVIEW = {
  id: "store-0042",
  name: "Vinamilk TP.HCM — CH 42",
  address: "123 Đường Nguyễn Huệ, Quận 1, TP.HCM",
  phone: "028 3822 0042",
  hours: "7:00 – 21:00 (T2–CN)",
  website: "https://vinamilk.com.vn/ch-42",
  gbpState: "Verify",
  kanban: "Cần thu thập bằng chứng",
  rating: 3.4,
  reviewCount: 38,
  oneStarCount: 9,
  evidenceSubmitted: 3,
  evidenceRequired: 4,
  deadline: "20/08/2026",
  progress: 65,
};

export const STORE_EVIDENCE_ITEMS = [
  {
    id: "license",
    label: "Giấy phép kinh doanh",
    status: "submitted" as const,
    file: "evidence/store-0042/gpkd.pdf",
    uploadedAt: "08/08/2026 10:12",
  },
  {
    id: "signage",
    label: "Ảnh bảng hiệu",
    status: "submitted" as const,
    file: "evidence/store-0042/bang-hieu.jpg",
    uploadedAt: "08/08/2026 10:18",
  },
  {
    id: "interior",
    label: "Ảnh nội thất",
    status: "submitted" as const,
    file: "evidence/store-0042/noi-that.jpg",
    uploadedAt: "09/08/2026 14:02",
  },
  {
    id: "video",
    label: "Video mặt tiền",
    status: "missing" as const,
    file: null,
    uploadedAt: null,
  },
];

export const STORE_PENDING_TASKS = [
  {
    id: "t1",
    title: "Quay video mặt tiền (bắt buộc)",
    due: "20/08/2026",
    href: "/demo/store-manager/evidence",
    urgent: true,
  },
  {
    id: "t2",
    title: "Kiểm tra N.A.P khớp giấy phép",
    due: "18/08/2026",
    href: "/demo/store-manager/nap",
    urgent: false,
  },
  {
    id: "t3",
    title: "Xem 9 đánh giá 1★ chưa phản hồi",
    due: "Hôm nay",
    href: "/demo/store-manager/reviews",
    urgent: true,
  },
];

export const STORE_NAP = {
  name: "Vinamilk TP.HCM — CH 42",
  address: "123 Đường Nguyễn Huệ, Quận 1, TP.HCM",
  phone: "028 3822 0042",
  hours: "7:00 – 21:00 (Thứ 2 – Chủ nhật)",
  category: "Cửa hàng sữa",
  website: "https://vinamilk.com.vn/ch-42",
  placeId: "ChIJ00000042",
  lastSynced: "12/08/2026 09:40 — chưa đẩy lên Google (chờ Verify)",
};

export const STORE_GBP_TIMELINE = [
  {
    id: "claim",
    label: "Claim listing",
    date: "01/08/2026",
    status: "done" as const,
    note: "Manager đã claim GBP cho cửa hàng.",
  },
  {
    id: "evidence",
    label: "Nộp bằng chứng",
    date: "Đang mở — hạn 20/08/2026",
    status: "current" as const,
    note: "Thiếu video mặt tiền. 3/4 checklist đã hoàn thành.",
  },
  {
    id: "review",
    label: "Google xét duyệt",
    date: "Chưa bắt đầu",
    status: "pending" as const,
    note: "Manager nộp hồ sơ lên Google sau khi checklist đủ.",
  },
  {
    id: "verified",
    label: "Verified",
    date: "Chưa bắt đầu",
    status: "pending" as const,
    note: "Sau khi Google duyệt, listing hiển thị công khai.",
  },
];

export const STORE_GUIDE_STEPS = [
  {
    step: 1,
    title: "Chuẩn bị giấy tờ",
    body: "Giấy phép kinh doanh đúng tên cửa hàng, ảnh bảng hiệu rõ chữ Vinamilk, ảnh nội thất ban ngày.",
  },
  {
    step: 2,
    title: "Quay video mặt tiền",
    body: "Quay liên tục 15–30 giây, bắt đầu từ đường phố, pan chậm tới bảng hiệu rồi vào cửa. Không cắt ghép, không nhạc nền.",
  },
  {
    step: 3,
    title: "Tải lên module Bằng chứng",
    body: "Kéo thả file vào checklist. Hệ thống lưu video/ảnh lên Cloudflare R2; metadata ghi bảng evidence (bản demo không ghi file).",
  },
  {
    step: 4,
    title: "Chờ Manager duyệt",
    body: "Agency PM kiểm tra checklist rồi nộp Claim / Verify lên Google. Bạn theo dõi trạng thái tại module Trạng thái hồ sơ.",
  },
];

export const STORE_GUIDE_FAQ = [
  {
    q: "Video cần quay như thế nào?",
    a: "Quay ngang, đủ sáng, thấy rõ bảng hiệu và cửa ra vào. Thời lượng 15–30 giây, không zoom giật, không overlay text.",
  },
  {
    q: "Tôi có được sửa N.A.P không?",
    a: "Store Manager chỉ xem N.A.P. Muốn sửa Name / Address / Phone phải gửi yêu cầu — Manager hoặc Admin mới Mass Update và sync Google.",
  },
  {
    q: "Khi nào Google gọi xác minh?",
    a: "Sau khi Manager nộp hồ sơ. Hãy đảm bảo SĐT cửa hàng nghe máy trong giờ mở cửa 7:00–21:00.",
  },
  {
    q: "Tôi có trả lời đánh giá được không?",
    a: "Không. Store Manager chỉ đọc đánh giá. Agency PM trả lời hộ theo SLA để đồng bộ giọng điệu thương hiệu.",
  },
];
